name: Swift

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Swift 5.5
      uses: fwal/setup-swift@d43a564349d1341cd990cfbd70d94d63b8899475
      with:
        swift-version: "5.5"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
